//Common JS --> Every file is a module (by default)
//MODULES --> Encapsulated code (only share with)

const names = require ('./4-names')
const sayHi = require ('./5-utils')
const data = require ('./6-alternative-flavor')
require(`./7-mind-grenade`)
sayHi(`susan`)
sayHi(names.ahmed)
sayHi(names.jamal)